### PR TITLE
Release 0.1.2

### PR DESCRIPTION
**Pull request by rossf7**

### CODE REVIEW

**Comment by tfussell** [comment]
Looks good. Give me just a few minutes to add my previous change to the changelog if you don't mind.

**Review by xh3b4sd — APPROVED** [review]

**Comment by rossf7** [comment]
@tfussell Yes sure. 👍

**Review by tfussell — APPROVED** [review]
Looks good.

**Comment by rossf7** [comment]
I just missed the headings in the changelog. Sorted now.

**Pull request merged**
