### PR TITLE
Add CredentialSecret to Azure

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/3316

* Add CredentialSecret to Azure Config
* Move CredentialSecret to common

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]

**Comment by xh3b4sd** [comment]
This PR broke compatibility in `kubernetesd` I have to fix this now and do even more yak shaving. How can this happen?

**Comment by xh3b4sd** [comment]
It did not happen because you renamed something. It did happen because the dependent code did not get updated.

**Comment by TheoBrigitte** [comment]
Is it my responsibility to update every repo making use of `apiextensions` when I introduce a breaking change there ?

**Comment by xh3b4sd** [comment]
Yes.

**Comment by TheoBrigitte** [comment]
Ackowledged

**Comment by xh3b4sd** [comment]
❤️

**Pull request merged**
