### PR TITLE
release: make types cluster scoped

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/5278

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]

**Comment by xh3b4sd** [comment]
Not too related to this PR but I found this. Why aren't the release types all scoped under the same domain? 

```
kubectl get crd
NAME                                     CREATED AT
...
releasecycles.release.giantswarm.io      2019-02-12T08:48:54Z
releases.core.giantswarm.io              2019-02-11T19:31:39Z
releases.release.giantswarm.io           2019-02-14T08:18:12Z
...
```

**Comment by kopiczko** [comment]
`releases.core.giantswarm.io` was removed from this repo a while ago. This is what `release-operator` was previously creating. We create CRDs while running operators but never delete them when they stop watching them (which makes sense because we couldn't redeploy).

**Comment by kopiczko** [comment]
I'm deleting this from all installations.

**Comment by xh3b4sd** [comment]
Ok, but why are not `Release` and `ReleaseCycle` kind in `release.giantswarm.io`?

**Comment by kopiczko** [comment]
> Ok, but why are not `Release` and `ReleaseCycle` kind in `release.giantswarm.io`?

They are. I'm deleting `releases.core.giantswarm.io`. This is the object that was removed.

**Comment by xh3b4sd** [comment]
Well yeah, but `ReleaseCycle` is in `releasecycles.release.giantswarm.io` and `Release` is in `releases.release.giantswarm.io`. I am asking because we try to figure the scope out for Node Pools. See https://github.com/giantswarm/giantswarm/pull/5683#discussion_r269762185.

**Comment by kopiczko** [comment]
The first part is name of the resource `releasecycles` or `releases`. The rest is the group `release.giantswarm.io` which is common for both.

In general we (magic) thought objects that should be versioned together should be in the same group.

This probably should be stated in some internal docs.

**Comment by xh3b4sd** [comment]
Uh ok. We will notice that at some point in Team Spirit then I guess.

**Comment by kopiczko** [comment]
Deleted `releases.core.giantswarm.io` on all installations.

**Pull request merged**
