### PR TITLE
Revert Add MD5 checksum for values to the chart CRD status

### PR DESCRIPTION
**Pull request by rossf7**
See https://github.com/giantswarm/apiextensions/pull/230#discussion_r278166144 we will use an annotation for storing the checksum.

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]
That makes sense to me, thanks.

**Review by MarcelMue — APPROVED** [review]
To labels we go :D

**Comment by kopiczko** [comment]
> To labels we go :D

Annotations

**Comment by MarcelMue** [comment]
> > To labels we go :D
> 
> Annotations

To annotations we go :D

**Comment by rossf7** [comment]
No problem and it improves the design. I did consider annotations but I turned right when I should have turned left.

**Pull request merged**
