### PR TITLE
update copyright date to 2020

### PR DESCRIPTION
**Pull request by xh3b4sd**
While fooling around I found this needs doing. No biggy.

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Comment by kopiczko** [comment]
Do we also need to change it here https://github.com/giantswarm/apiextensions/blob/78e994410a109864a20ff026a253214db491fa3a/LICENSE#L189

And in all other repos?

**Comment by xh3b4sd** [comment]
"IANAL" lol.

**Comment by kopiczko** [comment]
I pushed PRs to update year in template repos.

**Pull request merged**
