### PR TITLE
Add CAPI labels that will be used to filter CR's by version

### PR DESCRIPTION
**Pull request by fiunchinho**
We need to filter which CRs are watched by each deployed CAPI controller. The filtering is done via label.

Kubernetes label max length is 63 chars, we are safe.

## Checklist

- [ ] Consider SIG UX feedback.
- [X] Update changelog in CHANGELOG.md.
- [ ] If adding a new type, ensure that it is added to the [CRD unit tests](https://github.com/giantswarm/apiextensions/blob/d78aba91d578d56ef49f58e336035d35edc4e1b0/pkg/crd/crd_test.go#L9).

### CODE REVIEW

**Comment by fiunchinho** [comment]
We are experimenting with this "upgrade operator" that takes care of updating the labels for all the CR's. It knows which version to use because it reads that from the `Release` CR referenced by the `Cluster` CR release label. So basically, customers only need to use the release label in the Cluster CR, and the operator takes care of the rest.

**Comment by kubasobon** [comment]
Bonus question: what's our approach to `matchPolicy` ([documentation](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchpolicy))? Are labels granular enough, or do we need to redirect webhook calls based on CR version (`v1alphaX`).

**Comment by fiunchinho** [comment]
> enough

I don't really know how this works yet. But I'd say that a specific capi component release is coupled to a api version of the CRD, so filtering by label would be enough?

**Comment by mig4** [comment]
Stupid question, perhaps I'm confusing something, but according to https://github.com/kubernetes-sigs/cluster-api/pull/4119 shouldn't the label key always be `cluster.x-k8s.io/watch-filter`?

**Comment by fiunchinho** [comment]
> Stupid question, perhaps I'm confusing something, but according to [kubernetes-sigs/cluster-api#4119](https://github.com/kubernetes-sigs/cluster-api/pull/4119) shouldn't the label key always be `cluster.x-k8s.io/watch-filter`?

Oh so it's always the same label? I thought it was configurable. Closing this then.

**Comment by mig4** [comment]
> > Stupid question, perhaps I'm confusing something, but according to [kubernetes-sigs/cluster-api#4119](https://github.com/kubernetes-sigs/cluster-api/pull/4119) shouldn't the label key always be `cluster.x-k8s.io/watch-filter`?
> 
> Oh so it's always the same label? I thought it was configurable. Closing this then.

Double-check if I'm right, but yeah it seems that way.

**Pull request closed without merging**
