### PR TITLE
Add cluster status node labels

### PR DESCRIPTION
**Pull request by tuommaki**

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM, why do we need those labels? Or is it just a nice to have?

**Review by xh3b4sd — APPROVED** [review]

**Comment by marians** [comment]
It would be nice to find a YAML example/mock CR in the comments, to simply judge the changes based on the result.

**Review by pipo02mix — APPROVED** [review]
LGTM

**Comment by tuommaki** [comment]
> why do we need those labels? Or is it just a nice to have?

Initial driving need was to get node role information in Happa for each node that exists in order to count workers correctly but after checking what labels exist and discussion in #sig-ux it was also deemed to be generally useful. According to SEs there has been also customers asking for this info in `api`.

**Comment by tuommaki** [comment]
## Example of how status YAML would look like after this

```yaml
status:
  aws:
    availabilityZones:
    - name: eu-central-1b
      subnet:
        private:
          cidr: 10.1.1.0/25
        public:
          cidr: 10.1.1.128/25
  cluster:
    conditions:
    - lastHeartbeatTime: "2019-01-11T08:04:09.948589803Z"
      lastTransitionTime: "2019-01-11T08:04:09.948589803Z"
      status: "True"
      type: Created
    network:
      cidr: 10.1.1.0/24
    nodes:
    - lastHeartbeatTime: "2019-01-11T08:04:09.935796078Z"
      lastTransitionTime: "2019-01-11T08:04:09.935796182Z"
      labels:                                                                                                      
        beta.kubernetes.io/arch: amd64                                                                         
        beta.kubernetes.io/instance-type: m5.xlarge
        beta.kubernetes.io/os: linux                                                                                   
        failure-domain.beta.kubernetes.io/region: eu-central-1                                                     
        failure-domain.beta.kubernetes.io/zone: eu-central-1a                                                                
        ip: 10.1.1.31                          
        kubernetes.io/hostname: ip-10-1-1-31                                                              
        node-role.kubernetes.io/worker: ""                                                                         
        role: worker
      name: ip-10-1-1-31.eu-central-1.compute.internal
      version: 4.5.0
    - lastHeartbeatTime: "2019-01-11T08:04:09.935796986Z"
      lastTransitionTime: "2019-01-11T08:04:09.935797057Z"
      labels:                                                                                                      
        beta.kubernetes.io/arch: amd64                                                                         
        beta.kubernetes.io/instance-type: m5.xlarge
        beta.kubernetes.io/os: linux                                                                                   
        failure-domain.beta.kubernetes.io/region: eu-central-1                                                     
        failure-domain.beta.kubernetes.io/zone: eu-central-1a                                                                
        ip: 10.1.1.53                                       
        kubernetes.io/hostname: ip-10-1-1-53                                                              
        node-role.kubernetes.io/worker: ""                                                                         
        role: worker
      name: ip-10-1-1-53.eu-central-1.compute.internal
      version: 4.5.0
    - lastHeartbeatTime: "2019-01-11T08:04:09.935797528Z"
      lastTransitionTime: "2019-01-11T08:04:09.935797593Z"
      labels:                                                                                                      
        beta.kubernetes.io/arch: amd64                                                                         
        beta.kubernetes.io/instance-type: m5.xlarge
        beta.kubernetes.io/os: linux                                                                                   
        failure-domain.beta.kubernetes.io/region: eu-central-1                                                     
        failure-domain.beta.kubernetes.io/zone: eu-central-1a                                                                
        ip: 10.1.1.58                     
        kubernetes.io/hostname: ip-10-1-1-58                                                              
        node-role.kubernetes.io/worker: ""                                                                         
        role: worker
      name: ip-10-1-1-58.eu-central-1.compute.internal
      version: 4.5.0
    - lastHeartbeatTime: "2019-01-11T08:04:09.935798222Z"
      lastTransitionTime: "2019-01-11T08:04:09.935798291Z"
      labels:                                                                                                      
        beta.kubernetes.io/arch: amd64                                                                         
        beta.kubernetes.io/instance-type: m5.xlarge
        beta.kubernetes.io/os: linux                                                                                   
        failure-domain.beta.kubernetes.io/region: eu-central-1                                                     
        failure-domain.beta.kubernetes.io/zone: eu-central-1a                                                                
        ip: 10.1.1.93                                   
        kubernetes.io/hostname: ip-10-1-1-93                                                              
        node-role.kubernetes.io/worker: ""                                                                         
        role: worker
      name: ip-10-1-1-93.eu-central-1.compute.internal
      version: 4.5.0
    resources: null
    scaling:
      desiredCapacity: 0
    versions:
    - date: "0001-01-01T00:00:00Z"
      lastHeartbeatTime: "2019-01-11T08:04:09.966510703Z"
      lastTransitionTime: "2019-01-11T08:04:09.966510774Z"
      semver: 4.5.0
```

**Comment by tuommaki** [comment]
I'll now proceed with this, but if you have any criticism/comments/objections on this, give me a shout and we adjust this accordingly.

**Comment by xh3b4sd** [comment]
Can you please add the example to the godoc? Some time back we said this would be very helpful for SIG UX to reason about the implications of structural changes.

**Comment by tuommaki** [comment]
Would this: https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/provider/v1alpha1/status_types.go#L28 be the best place for the comment?

**Comment by xh3b4sd** [comment]
I think so. Just the type that gets rendered in the example. Maybe with a note that in the example the AWS block is also shown and that we actually want to try to design the whole status as provider independent as possible.

**Comment by pipo02mix** [comment]
awesome :)

**Pull request merged**
