### PR TITLE
Add azure host cluster network name

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards https://github.com/giantswarm/azure-operator/issues/115

Provide host cluster virtual network's name in AzureConfig

### CODE REVIEW

**Comment by rossf7** [comment]
I'm having the same problem in my `apiextensions` PR. The fake clientset being generated is triggering go vet warnings.

```
go vet ./...'
# github.com/giantswarm/apiextensions/pkg/clientset/versioned/fake
pkg/clientset/versioned/fake/clientset_generated.go:48: literal copies lock value from fakePtr: github.com/giantswarm/apiextensions/vendor/k8s.io/client-go/testing.Fake
```

I can fix manually but how can we fix via the code generator? 
https://github.com/giantswarm/apiextensions/pull/58/commits/c965ee54cf670e495eb4be1eaad66f688e6ed759

This was based on this k8s PR.
https://github.com/kubernetes/kubernetes/pull/60584/files

**Comment by kopiczko** [comment]
`go vet` was removed from architect workflow recently. Let's wait for https://github.com/giantswarm/architect/pull/203 to be merged.

**Comment by rossf7** [comment]
@kopiczko Ack. Thanks for the info!

**Comment by xh3b4sd** [comment]
Does the problem only occur on `go vet` or also `go test`?

**Comment by rossf7** [comment]
Just on `go vet`.

**Comment by xh3b4sd** [comment]
Ack. Note that I want to have two more approvals on my architect PR since it is quite controversial.

**Pull request merged**
