### PR TITLE
sets default namespace for CRs

### PR DESCRIPTION
**Pull request by xh3b4sd**

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM

**Review by tuommaki — APPROVED** [review]
FMI: This is for the Helm weirdness?

**Comment by xh3b4sd** [comment]
Somehow yes. We install via our `e2e-harness/pkg/release` package and this has the `giantswarm` namespace configured. So right now the CR is in this namespace but the e2e tests expect it in `default`.

**Comment by kopiczko** [comment]
Why `KVMConfig` isn't changed as well?

**Comment by xh3b4sd** [comment]
On KVM we have no encapsulation on the CI builds and they are namespaced very differently. 😕

**Comment by xh3b4sd** [comment]
The direction should rather be to get rid of the namespacing weirdness I feel like. for now we only need this because of the isolation issues on KVM which we want to address in the future with more dynamic control plane management.

**Comment by MarcelMue** [comment]
I think I was wrong here, the `kvmconfig` is also in the default namespace - we use the labelselector to choose the right one instead of the namespace. I will provide a PR to add the `default` namespace to kvm.

**Pull request merged**
