### PR TITLE
Use CRD v1

### PR DESCRIPTION
**Pull request by sslavic**
Aligns with https://github.com/giantswarm/k8sclient/pull/67 so they can be used together in operatorkit.

## Checklist

- [ ] Consider SIG UX feedback.
- [ ] Update changelog in CHANGELOG.md.
- [ ] If adding a new type, ensure that it is added to the [CRD unit tests](https://github.com/giantswarm/apiextensions/blob/d78aba91d578d56ef49f58e336035d35edc4e1b0/pkg/crd/crd_test.go#L9).

### CODE REVIEW

**Comment by sslavic** [comment]
- k8sclient was switched to use CRD v1 via https://github.com/giantswarm/k8sclient/pull/67
- our apiextensions has somewhat related update "Support v1 and v1beta1 concurrently" https://github.com/giantswarm/apiextensions/pull/435
- trying to use both of those libs together in operatorkit does not compile https://circleci.com/gh/giantswarm/operatorkit/7104
- our apiextensions update had in description
> In this way the NewAzureConfigCRD() function, for example, determines which version is loaded and we can transition one-by-one.

Given all above, probably I'm missing something here why all `New*CRD()` did not get changed to CRD v1 in single PR like this. Here's that PR, looking forward to your feedback.

**Comment by xh3b4sd** [comment]
You may want to check https://github.com/giantswarm/giantswarm/issues/9963#issuecomment-620048484. We discussed the necessary steps you need to take and recorded our session.

**Comment by tfussell** [comment]
`KVMConfig`, `KVMClusterConfig`, `FlannelConfig`, and `StorageConfig` are being graduated here https://github.com/giantswarm/apiextensions/pull/497 `AWSClusterConfig` won't be graduated according to https://github.com/giantswarm/giantswarm/issues/9963 `CertConfig` and `DrainerConfig` are already done. That just leaves `ChartConfig` which should be handled by batman at some point. This can probably be closed.

**Comment by rossf7** [comment]
> That just leaves ChartConfig which should be handled by batman at some point.

@tfussell chartconfig CRD is legacy it is replaced by the app and chart CRDs. We're waiting on customers to upgrade TCs so we can delete it but as we know that takes ages.

What is the impact if we don't migrate it?

**Comment by tfussell** [comment]
> What is the impact if we don't migrate it?

CRD v1beta1 is being removed in Kubernetes 1.19 which will be released very soon. We won't be able to edit the CRD (without creating a special branch of apiextensions), use validation, or defaulting. If those are all okay, I think it doesn't need to be upgraded.

**Comment by rossf7** [comment]
@tfussell Thanks for clarifying and in that case we're fine. 🎉 

chartconfig CRD is only installed in tenant clusters and from 9.0.1 onwards we only use chart CRDs.

**Comment by xh3b4sd** [comment]
Do we want to go with this PR or can we close it?

**Comment by tfussell** [comment]
> Do we want to go with this PR or can we close it?

We're close to being able to get rid of v1beta1 CRDs entirely at which point we can get rid of much of this backward compatibility. Moreover, we only use these CRDs in opsctl now so we could move some or all of the CRD management code there. In short, I'd say we should close it unless someone needs these V1 functions very soon.

**Comment by rossf7** [comment]
Migration from v1beta1 is nearly done. We can finish that up in fresh PRs. Closing.

**Pull request closed without merging**
