### PR TITLE
Add silence crd

### PR DESCRIPTION
**Pull request by corest**
Towards https://github.com/giantswarm/giantswarm/issues/14116

We want to start managing silences in alertmanager in gitops style (syncing CRs from central repo where we store CRs)
This is part of implementation.

## Checklist

- [x] Consider SIG UX feedback.
- [x] Update changelog in CHANGELOG.md.
- [ ] If adding a new type, ensure that it is added to the [CRD unit tests](https://github.com/giantswarm/apiextensions/blob/d78aba91d578d56ef49f58e336035d35edc4e1b0/pkg/crd/crd_test.go#L9).

### CODE REVIEW

**Review by fiunchinho — CHANGES_REQUESTED** [review]
Please update the changelog.

**Review by fiunchinho — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]
Works for me

**Review by mig4 — APPROVED** [review]

**Comment by pipo02mix** [comment]
Should it not have a field for expiration?

**Comment by corest** [comment]
@pipo02mix no, while CR exists - silence exists

**Pull request merged**
