### PR TITLE
Add sample CRs for Azure Cluster API types.

### PR DESCRIPTION
**Pull request by whites11**
## Checklist

- [x] Consider SIG UX feedback.
- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by axbarsan — APPROVED** [review]

**Comment by marians** [comment]
I am missing some code that generates these examples. Normally the examples are generated from unit tests.

**Comment by marians** [comment]
Here for example: https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/provider/v1alpha1/aws_types_test.go#L76

**Comment by whites11** [comment]
> I am missing some code that generates these examples. Normally the examples are generated from unit tests.

These are upstream CRDs, does it still apply? Where should I store the test if I don't have the Go file defining its types?

**Comment by marians** [comment]
> These are upstream CRDs

Sorry, I missed that part. Then I don't know from the top of my head. Do we have precedence for this? Any other third party CRDs we are building examples for?

**Comment by whites11** [comment]
> > These are upstream CRDs
> 
> Sorry, I missed that part. Then I don't know from the top of my head. Do we have precedence for this? Any other third party CRDs we are building examples for?

The AWS CAPI types are external AFAIK, but the go structs are defined in  `apiextensions` so that's not what we're doing with Azure CRDs.
Seems to be a first time to me.

**Comment by marians** [comment]
I'd say, let's try it then.

**Review by marians — APPROVED** [review]

**Pull request merged**
