### PR TITLE
Add AWSCNIPrefixDelegation annotation

### PR DESCRIPTION
**Pull request by njuettner**
This allows customers enabling the prefix delegation for AWS CNI which will be introduced within AWS release v16.1.
Enabling this feature will improve the speed of IP assignment on nitro based instances.

See https://github.com/aws/amazon-vpc-cni-k8s#enable_prefix_delegation-v190

Addresses: https://github.com/giantswarm/roadmap/issues/396

## Checklist

- [ ] Consider SIG UX feedback.
- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by fiunchinho — CHANGES_REQUESTED** [review]
Let's use https://github.com/giantswarm/k8smetadata instead

**Comment by njuettner** [comment]
> Let's use https://github.com/giantswarm/k8smetadata instead

Shall this be used for the current GS project? I can't see k8smetadata is used in `aws-operator`?

**Comment by njuettner** [comment]
This would move we need to move all AWSCNI annotations into k8smetadata otherwise we would have a split between the annotation settings on AWS CNI.

**Comment by fiunchinho** [comment]
> > Let's use https://github.com/giantswarm/k8smetadata instead
> 
> Shall this be used for the current GS product? I can't see k8smetadata is used in `aws-operator`?

Yes, the idea is to migrate all labels and annotations to that repo to reduce dependency on the `apiextensions` repo. In `aws-operator`'s case it doesn't matter that much since it needs the dependency anyway, but I'd vote for use `k8smetadata` everywhere to avoid confusion.

**Comment by fiunchinho** [comment]
> This would move we need to move all AWSCNI annotations into k8smetadata otherwise we would have a split between the annotation settings on AWS CNI.
> 
> Sorry, I just saw we already have the settings there, but I guess nobody updated the aws-operator

yeah I guess so.

**Comment by njuettner** [comment]
@fiunchinho unfortunately we still need this PR merged, I think we need it to update the docs, see https://docs.giantswarm.io/ui-api/management-api/crd/awsclusters.infrastructure.giantswarm.io/#annotation-details-v1alpha2

**Comment by njuettner** [comment]
We need to also add it here for the crd-docs-generator

**Review by fiunchinho — APPROVED** [review]
Alright then.

**Pull request merged**
