### PR TITLE
add upgrade annotations

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/18077

I am using these annotations for now while working on the upgrade-schedule-operator. This won't be merged until other things are in order so open to other suggestions.

## Checklist

- [ ] Consider SIG UX feedback.
- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by calvix** [comment]
i wonder if this should be AWS only, as it could be useful for other providers as well and the logic should does not need provider specific info

**Comment by anvddriesch** [comment]
Yeah. If the upgrade mechanism is exactly the same on all providers there is nothing stopping us from making this a shared thing. We could still try it out on AWS first.

**Comment by calvix** [comment]
> Yeah. If the upgrade mechanism is exactly the same on all providers there is nothing stopping us from making this a shared thing. We could still try it out on AWS first.

yeah, we can definitely alpha test it on AWS but then I would drop the was prefix from the annotation and maybe put it in a different file.

**Comment by njuettner** [comment]
> > Yeah. If the upgrade mechanism is exactly the same on all providers there is nothing stopping us from making this a shared thing. We could still try it out on AWS first.
> 
> yeah, we can definitely alpha test it on AWS but then I would drop the AWS prefix from the annotation and maybe put it in a different file.

I agree. The annotation should be set on the Cluster CR, this should be independent of the infrastructure provider. I would move it to https://github.com/giantswarm/apiextensions/blob/master/pkg/annotation/cluster.go if possible. The operator should be anyway watch on Cluster CR, right?

**Comment by anvddriesch** [comment]
Yeah, the operator is watching the cluster CR. I will move and rename the annotations! :)

**Review by njuettner — APPROVED** [review]

**Review by calvix — APPROVED** [review]

**Comment by fiunchinho** [comment]
Remember that we decided on not adding more annotations and labels to `apiextensions` to decouple CRDs versioning from them. Can you add this to https://github.com/giantswarm/k8smetadata ?

**Comment by anvddriesch** [comment]
Thanks for the heads up Jose! :) I will add it.

**Pull request merged**
