### PR TITLE
Add secret to chartconfig

### PR DESCRIPTION
**Pull request by MarcelMue**
Would be nice if you can take a look @rossf7 

Towards https://github.com/giantswarm/giantswarm/issues/3390

### CODE REVIEW

**Review by rossf7 — APPROVED** [review]
Nice. Using the same type of data structure for the secret makes sense to me.

**Comment by MarcelMue** [comment]
I had to resolve some merge conflicts, can you take a look again if everything is fine for you @rossf7 ?
Just being safe here.

**Comment by rossf7** [comment]
@MarcelMue Yes sure. All looks fine to me. As long as everything from `/scripts/gen.sh` got added then we're good here.

**Comment by MarcelMue** [comment]
Ack, I did that. Merging.

**Pull request merged**
