### PR TITLE
Add types for githubsearchindices.example.giantswarm.io

### PR DESCRIPTION
**Pull request by marians**
This should add types required for CRs/CRDs handled by [github-search-index-operator](https://github.com/giantswarm/github-search-index-operator).

### CODE REVIEW

**Comment by rossf7** [comment]
@marians I added sig-operator. Anyone in the SIG that is onboarded can review this IMO.

**Comment by xh3b4sd** [comment]
you also need to add your type to `register.go`. Then you will notice that this does not compile as your types do not implement `runtime.Object`. To fix that you need to run `./scripts/gen.sh`. Also note that there is a new way of defining the CRDs. Check how releases do that, or the new infrastructure types.

**Comment by marians** [comment]
So I did the generation part (sorry for not reading README properly) and now am here:

```
pkg/apis/example/v1alpha1/zz_generated.deepcopy.go:183:19: in.LastCommitTime.DeepCopyInto undefined (type time.Time has no field or method DeepCopyInto)
```

One of the attributes in my CR is defined as time.Time. Should I make it a string instead?

**Comment by xh3b4sd** [comment]
Check the infrastructure types. There is a `DeepCopyTime` type to work around that problem.

**Comment by MarcelMue** [comment]
Also here:
https://github.com/giantswarm/apiextensions/blob/master/pkg/apis/provider/v1alpha1/deep_copy.go

**Comment by marians** [comment]
Thanks! I now duplicated this into the examples/v1alpha1 folder. Let me know if that needs de-duplication.

**Comment by rossf7** [comment]
@marians We agreed to drop this operator and the CRD but the CRD got missed.

https://github.com/giantswarm/giantswarm/issues/6570#issuecomment-539909986

But it does no harm to update it IMO.

**Comment by xh3b4sd** [comment]
Is this PR still valid? Can we merge or close?

**Pull request closed without merging**
