### PR TITLE
AWSControlPlane: add descriptions, remove unused status

### PR DESCRIPTION
**Pull request by marians**
Towards https://github.com/giantswarm/giantswarm/issues/8804

This adds descriptions to properties.

Also it removes the unused status part.

## Checklist

- [ ] Consider SIG UX feedback.
- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by marians** [comment]
There are still references to the removed `AWSControlPlaneStatus` in generated code it seems. How to get rid of all?

**Comment by xh3b4sd** [comment]
I pushed a commit in here to fix the deep copy generation. This also fixed the problem with that `github.com/` directory which we deleted at the end of the script. That was generated and contained the deep copy functions. I just dropped the output base and use the default. I think this makes sense. FYI @tfussell

**Comment by marians** [comment]
Thanks @xh3b4sd ! Now the PR is actually ready for review. :)

**Comment by tfussell** [comment]
> I pushed a commit in here to fix the deep copy generation. This also fixed the problem with that `github.com/` directory which we deleted at the end of the script. That was generated and contained the deep copy functions. I just dropped the output base and use the default. I think this makes sense. FYI @tfussell

@xh3b4sd Nice one. The script looks cleaner now too.

**Pull request merged**
