### PR TITLE
app: fix yaml output

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/6847

This PR intends to fix the generated yaml output for App CR.

It does so by setting the `omitempty` field tag on optional fields and using pointer for those.

yaml output without this PR:
```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: foo-bar
  namespace: giantswarm
spec:
  catalog: baz
  config:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: foo
  namespace: giantswarm
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: bar
status:
  appVersion: ""
  release:
    lastDeployed: "0001-01-01T00:00:00Z"
    status: ""
  version: ""
```

yaml output with this PR:
```yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  creationTimestamp: null
  labels:
    app-operator.giantswarm.io/version: 1.0.0
  name: foo-bar
  namespace: giantswarm
spec:
  catalog: baz
  kubeConfig:
    inCluster: true
  name: foo
  namespace: giantswarm
  version: bar
status: {}
```

### CODE REVIEW

**Comment by kopiczko** [comment]
I'd use `github.com/ghodss/yaml` instead. It's already introduced in this repo by @sslavic. See https://github.com/giantswarm/apiextensions/pull/264#discussion_r313258648 if you are interested in details.

**Review by tomahawk28 — APPROVED** [review]

**Comment by TheoBrigitte** [comment]
> I'd use `github.com/ghodss/yaml` instead. It's already introduced in this repo by @sslavic. See [#264 (comment)](https://github.com/giantswarm/apiextensions/pull/264#discussion_r313258648) if you are interested in details.

Removed the yaml field tags. PTALA

**Review by kopiczko — APPROVED** [review]

**Comment by rossf7** [comment]
@TheoBrigitte I like these changes a lot but they need some code changes in app-operator because of the change from structs to pointers.

Also my previous change in https://github.com/giantswarm/apiextensions/pull/279 doesn't work when deployed. e2e is green but the operator crashes when deployed. 😞 

```
E 09/04 17:55:09 /apis/core.giantswarm.io/v1alpha1/namespaces/default/awsclusterconfigs/8353p-aws-cluster-config appmigrationv20 stop reconciliation due to error | operatorkit/controller/controller.go:371 | controller=cluster-operator | event=update | loop=14 | version=4802813
	/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/controller/controller.go:552:
	/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/metricsresource/resource_wrapper.go:39:
	/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/retryresource/resource_wrapper.go:79:
	/go/src/github.com/giantswarm/cluster-operator/vendor/github.com/giantswarm/operatorkit/resource/wrapper/retryresource/resource_wrapper.go:67:
	/go/src/github.com/giantswarm/cluster-operator/pkg/v20/resource/appmigration/create.go:74:
	/go/src/github.com/giantswarm/cluster-operator/pkg/v20/resource/appmigration/create.go:167:
	resource name may not be empty
```

Maybe the fixes here improve the situation but not certain. What can we do about this?

cc @xh3b4sd @kopiczko @sslavic @tomahawk28

**Comment by kopiczko** [comment]
> because of the change from structs to pointers

What do you mean? Is this a change in app-operator? I'm happy to talk.

**Comment by rossf7** [comment]
Yes, the changes in app-operator are not big. Minor change in the status resource and some UTs. 

My worry is more the error I posted. It's related to updating the existing CRDs as it doesn't happen in e2e. I'm not sure how to fix it.

@sslavic Maybe you could help here?  As you worked on the chart CRD changes. If not I can try to check on it tomorrow.

**Comment by TheoBrigitte** [comment]
This PR only changed App CR, I don't understand how this change affects the existing CRD ?

**Comment by kopiczko** [comment]
@rossf7 Now I see the pointers. My eyes missed those little `*` characters. Yeah this is controversial and I have mixed feelings about that.

**Comment by rossf7** [comment]
Yes since the app CR is customer-facing I think it's worth putting some extra effort in. I'm not sure it's worth it for internal-only CRs. Maybe we need some guidelines for that in sig-operator?

cc @xh3b4sd 

The changes in app-operator did get pretty big. I need to do another manual test but then they can be merged.

https://github.com/giantswarm/app-operator/pull/136

**Comment by rossf7** [comment]
I'm fine with reverting but I don't have time to work on it today. @kopiczko could you or @TheaMarie help with this?

My preference would be to also remove the YAML changes. As they broke when I deployed them and we got a ton of pages.

My take away is adding the OpenAPI validation rules is complex. We need to be sure the approach makes sense and doesn't break stuff before we roll this out.

**Comment by kopiczko** [comment]
I'm uncertain what to think about this. On the one hand it makes sense to have pointers because otherwise `omitempty` doesn't work. On the other hand this is ugly and breaks a lot of things. It would be good to discuss the approach with SIG first.

**Comment by kopiczko** [comment]
I'm happy to help but let's have an agreement first.

**Comment by TheoBrigitte** [comment]
Happy to help also 🤚

**Comment by rossf7** [comment]
What about we go back to https://github.com/giantswarm/apiextensions/pull/281?

So we use structs and remove the pointers change from cluster-operator. Help with that would be much appreciated. ❤️ 

I'll put a card in the SIG board and maybe we also need a session on this.

**Comment by rossf7** [comment]
I'll keep my app-operator PR open but not merge it until we've decided what we want to do.

**Pull request merged**
