### PR TITLE
Remove generated clientset

### PR DESCRIPTION
**Pull request by tfussell**
As part of the modernizing of `apiextensions`, I thought it would be helpful to remove the generated typed clients. So far it seems we can use `controller-runtime` client for everything (except evicting pods).

## Checklist

- [x] Consider SIG UX feedback.
- [x] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]
This is the good stuff

image

**Comment by marians** [comment]
Sorry, no idea what this really means and on what basis to review.

**Review by MarcelMue — APPROVED** [review]

**Review by anvddriesch — APPROVED** [review]

**Comment by fiunchinho** [comment]
> Sorry, no idea what this really means and on what basis to review.

Using the code generation tools from upstream we were generating different clientsets for the different types (CRDs) that we registered in the k8s API. [A clientset is a http client](https://stackoverflow.com/questions/48388077/what-is-a-kubernetes-client-go-clientset) that knows how to talk to the k8s API to work with that specific type.

But the [controller-runtime folks](https://github.com/kubernetes-sigs/controller-runtime) offer a generic way of talking to the k8s API using the client on their controller-runtime library, [which doesn't need the typed client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/example_test.go). This is mostly what we use today in our operators and libraries.

**Comment by marians** [comment]
ACK, thanks for the info. Big breaking change, right? Will be released as a new Major version, I guess?

**Comment by tfussell** [comment]
> ACK, thanks for the info. Big breaking change, right? Will be released as a new Major version, I guess?

Definitely. There will be some other breaking changes from my other PR as well.

**Pull request merged**
